import type { CatalogSource, SourceCategory } from "./sources.js";

type Seed = {
  slug: string;
  name: string;
  homepageUrl: string;
  endpoint: string;
  region: string;
  language: string;
  category: SourceCategory;
  acquisition: Extract<CatalogSource["acquisition"], "html" | "rss">;
  topics: string[];
  identityHosts: string[];
};

const seeds: Seed[] = [
  {
    slug: "meta-llama-updates",
    name: "Meta Llama Repository Updates",
    homepageUrl: "https://github.com/meta-llama/llama-models",
    endpoint: "https://github.com/meta-llama/llama-models/commits/main.atom",
    region: "US",
    language: "en",
    category: "open-source",
    acquisition: "rss",
    topics: ["meta", "llama", "open-model", "model-release"],
    identityHosts: ["meta.com", "ai.meta.com", "github.com"],
  },
  {
    slug: "mistral-inference-updates",
    name: "Mistral Inference Repository Updates",
    homepageUrl: "https://github.com/mistralai/mistral-inference",
    endpoint: "https://github.com/mistralai/mistral-inference/commits/main.atom",
    region: "EU",
    language: "en",
    category: "open-source",
    acquisition: "rss",
    topics: ["mistral", "inference", "open-model", "deployment"],
    identityHosts: ["mistral.ai", "github.com"],
  },
  {
    slug: "cohere-release-notes",
    name: "Cohere Release Notes",
    homepageUrl: "https://docs.cohere.com/changelog/",
    endpoint: "https://docs.cohere.com/changelog/",
    region: "GLOBAL",
    language: "en",
    category: "frontier-lab",
    acquisition: "html",
    topics: ["cohere", "command", "enterprise", "rag", "agent"],
    identityHosts: ["cohere.com", "docs.cohere.com"],
  },
  {
    slug: "perplexity-changelog",
    name: "Perplexity API Changelog",
    homepageUrl: "https://docs.perplexity.ai/changelog",
    endpoint: "https://docs.perplexity.ai/changelog",
    region: "US",
    language: "en",
    category: "frontier-lab",
    acquisition: "html",
    topics: ["perplexity", "sonar", "search", "api", "citations"],
    identityHosts: ["perplexity.ai", "docs.perplexity.ai"],
  },
  {
    slug: "bytedance-seed-blog",
    name: "ByteDance Seed Model News",
    homepageUrl: "https://seed.bytedance.com/en/blog",
    endpoint: "https://seed.bytedance.com/en/blog",
    region: "CN",
    language: "en",
    category: "china-lab",
    acquisition: "html",
    topics: ["bytedance", "seed", "doubao", "agent", "multimodal"],
    identityHosts: ["bytedance.com", "seed.bytedance.com"],
  },
  {
    slug: "tencent-hunyuan-updates",
    name: "Tencent Hunyuan Repository Updates",
    homepageUrl: "https://github.com/Tencent-Hunyuan/HY-WorldPlay",
    endpoint: "https://github.com/Tencent-Hunyuan/HY-WorldPlay/commits/main.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["tencent", "hunyuan", "world-model", "video", "3d"],
    identityHosts: ["tencent.com", "hunyuan.tencent.com", "github.com"],
  },
  {
    slug: "baidu-ernie-updates",
    name: "Baidu ERNIE Repository Updates",
    homepageUrl: "https://github.com/PaddlePaddle/ERNIE",
    endpoint: "https://github.com/PaddlePaddle/ERNIE/commits/release/v1.5.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["baidu", "ernie", "paddlepaddle", "open-model"],
    identityHosts: ["baidu.com", "ernie.baidu.com", "github.com"],
  },
  {
    slug: "stepfun-model-updates",
    name: "StepFun Model Repository Updates",
    homepageUrl: "https://github.com/stepfun-ai/Step-3.5-Flash",
    endpoint: "https://github.com/stepfun-ai/Step-3.5-Flash/commits/main.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["stepfun", "step", "agent", "reasoning", "open-model"],
    identityHosts: ["stepfun.com", "github.com"],
  },
  {
    slug: "01ai-yi-updates",
    name: "01.AI Yi Repository Updates",
    homepageUrl: "https://github.com/01-ai/Yi",
    endpoint: "https://github.com/01-ai/Yi/commits/main.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["01ai", "yi", "bilingual", "open-model"],
    identityHosts: ["01.ai", "lingyiwanwu.com", "github.com"],
  },
  {
    slug: "baichuan-m3-updates",
    name: "Baichuan M3 Repository Updates",
    homepageUrl: "https://github.com/baichuan-inc/Baichuan-M3-235B",
    endpoint: "https://github.com/baichuan-inc/Baichuan-M3-235B/commits/main.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["baichuan", "medical", "reasoning", "open-model"],
    identityHosts: ["baichuan-ai.com", "github.com"],
  },
  {
    slug: "modelbest-minicpm-updates",
    name: "OpenBMB MiniCPM Repository Updates",
    homepageUrl: "https://github.com/OpenBMB/MiniCPM",
    endpoint: "https://github.com/OpenBMB/MiniCPM/commits/main.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["modelbest", "openbmb", "minicpm", "on-device", "open-model"],
    identityHosts: ["modelbest.cn", "openbmb.cn", "github.com"],
  },
  {
    slug: "sensetime-news-en",
    name: "SenseTime Model News",
    homepageUrl: "https://www.sensetime.com/en/news/",
    endpoint: "https://www.sensetime.com/en/news/",
    region: "CN",
    language: "en",
    category: "china-lab",
    acquisition: "html",
    topics: ["sensetime", "sensenova", "multimodal", "agent", "open-model"],
    identityHosts: ["sensetime.com"],
  },
  {
    slug: "iflytek-spark-docs",
    name: "iFlytek Spark Documentation",
    homepageUrl: "https://xinghuo.xfyun.cn/doc/spark-guide/spark.html",
    endpoint: "https://xinghuo.xfyun.cn/doc/spark-guide/spark.html",
    region: "CN",
    language: "zh-CN",
    category: "china-lab",
    acquisition: "html",
    topics: ["iflytek", "spark", "xinghuo", "reasoning", "education"],
    identityHosts: ["iflytek.com", "xfyun.cn"],
  },
  {
    slug: "minimax-model-releases",
    name: "MiniMax Model Release Notes",
    homepageUrl: "https://platform.minimaxi.com/docs/release-notes/models",
    endpoint: "https://platform.minimaxi.com/docs/release-notes/models",
    region: "CN",
    language: "zh-CN",
    category: "china-lab",
    acquisition: "html",
    topics: ["minimax", "m2", "agent", "coding", "model-release"],
    identityHosts: ["minimaxi.com", "platform.minimaxi.com"],
  },
  {
    slug: "moonshot-kimi-updates",
    name: "Moonshot Kimi K2.5 Repository Updates",
    homepageUrl: "https://github.com/MoonshotAI/Kimi-K2.5",
    endpoint: "https://github.com/MoonshotAI/Kimi-K2.5/commits/master.atom",
    region: "CN",
    language: "zh-CN",
    category: "open-source",
    acquisition: "rss",
    topics: ["moonshot", "kimi", "multimodal", "agent-swarm", "open-model"],
    identityHosts: ["moonshot.ai", "moonshot.cn", "kimi.com", "github.com"],
  },
];

export const ecosystemEvidenceSources20260714: CatalogSource[] = seeds.map((seed) => ({
  ...seed,
  adapter: seed.acquisition === "rss" ? "rss" : "web-scraper",
  tier: 1,
  role: "primary",
  authorityScore: 92,
  qualityScore: 84,
  enabled: false,
  lifecycleStatus: "shadow",
  maintenanceStatus: "candidate",
  cadence: "6h",
  licenseNote:
    "Official public metadata and short excerpts only; preserve provenance, link to the original, and never republish full source content.",
}));
