import type { CatalogSource, SourceCategory } from "./sources.js";

type SourceRole = CatalogSource["role"];

type ReleaseSeed = readonly [
  slug: string,
  name: string,
  repository: string,
  region: string,
  category: SourceCategory,
  role: SourceRole,
  topics: readonly string[],
  tier?: 1 | 2,
];

type FeedSeed = readonly [
  slug: string,
  name: string,
  homepageUrl: string,
  endpoint: string,
  region: string,
  category: SourceCategory,
  role: SourceRole,
  topics: readonly string[],
  tier?: 1 | 2,
];

const releaseSeeds: ReleaseSeed[] = [
  // Agent runtimes, SDKs and protocols (30).
  [
    "openai-agents-python-releases",
    "OpenAI Agents SDK for Python",
    "openai/openai-agents-python",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "sdk", "python"],
  ],
  [
    "openai-agents-js-releases",
    "OpenAI Agents SDK for JavaScript",
    "openai/openai-agents-js",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "sdk", "javascript"],
  ],
  [
    "openai-go-releases",
    "OpenAI Go SDK",
    "openai/openai-go",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["api", "sdk", "go"],
  ],
  [
    "openai-java-releases",
    "OpenAI Java SDK",
    "openai/openai-java",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["api", "sdk", "java"],
  ],
  [
    "openai-dotnet-releases",
    "OpenAI .NET SDK",
    "openai/openai-dotnet",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["api", "sdk", "dotnet"],
  ],
  [
    "anthropic-go-releases",
    "Anthropic Go SDK",
    "anthropics/anthropic-sdk-go",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["claude", "api", "sdk", "go"],
  ],
  [
    "anthropic-java-releases",
    "Anthropic Java SDK",
    "anthropics/anthropic-sdk-java",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["claude", "api", "sdk", "java"],
  ],
  [
    "google-adk-python-releases",
    "Google Agent Development Kit for Python",
    "google/adk-python",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "sdk", "python", "gemini"],
  ],
  [
    "google-adk-js-releases",
    "Google Agent Development Kit for JavaScript",
    "google/adk-js",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "sdk", "javascript", "gemini"],
  ],
  [
    "firebase-genkit-releases",
    "Firebase Genkit",
    "firebase/genkit",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "application-framework", "firebase"],
  ],
  [
    "pydantic-ai-releases",
    "Pydantic AI",
    "pydantic/pydantic-ai",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "python", "structured-output"],
  ],
  [
    "smolagents-releases",
    "Hugging Face smolagents",
    "huggingface/smolagents",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "open-source", "huggingface"],
  ],
  [
    "haystack-releases",
    "Haystack",
    "deepset-ai/haystack",
    "EU",
    "agent-devtool",
    "primary",
    ["agent", "rag", "application-framework"],
  ],
  [
    "camel-ai-releases",
    "CAMEL",
    "camel-ai/camel",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["multi-agent", "agent", "research"],
  ],
  [
    "ag2-releases",
    "AG2",
    "ag2ai/ag2",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["multi-agent", "agent", "application-framework"],
  ],
  [
    "llama-stack-releases",
    "Llama Stack",
    "meta-llama/llama-stack",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "open-model", "api"],
  ],
  [
    "mastra-releases",
    "Mastra",
    "mastra-ai/mastra",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "typescript", "workflow"],
  ],
  [
    "mem0-releases",
    "Mem0",
    "mem0ai/mem0",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "memory", "personalization"],
  ],
  [
    "letta-releases",
    "Letta",
    "letta-ai/letta",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "memory", "stateful-agent"],
  ],
  [
    "agentscope-releases",
    "ModelScope AgentScope",
    "modelscope/agentscope",
    "CN",
    "china-lab",
    "primary",
    ["agent", "multi-agent", "modelscope"],
  ],
  [
    "langsmith-sdk-releases",
    "LangSmith SDK",
    "langchain-ai/langsmith-sdk",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "observability", "evaluation"],
  ],
  [
    "microsoft-agent-framework-releases",
    "Microsoft Agent Framework",
    "microsoft/agent-framework",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["agent", "enterprise", "sdk"],
  ],
  [
    "microsoft-graphrag-releases",
    "Microsoft GraphRAG",
    "microsoft/graphrag",
    "GLOBAL",
    "agent-devtool",
    "research",
    ["rag", "knowledge-graph", "research"],
  ],
  [
    "dspy-releases",
    "DSPy",
    "stanfordnlp/dspy",
    "US",
    "research-eval",
    "research",
    ["language-model-programming", "optimization", "research"],
  ],
  [
    "outlines-releases",
    "Outlines",
    "dottxt-ai/outlines",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["structured-generation", "inference", "developer"],
  ],
  [
    "mcp-servers-releases",
    "Model Context Protocol Servers",
    "modelcontextprotocol/servers",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["mcp", "protocol", "server"],
  ],
  [
    "mcp-registry-releases",
    "Model Context Protocol Registry",
    "modelcontextprotocol/registry",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["mcp", "protocol", "registry"],
  ],
  [
    "mcp-inspector-releases",
    "Model Context Protocol Inspector",
    "modelcontextprotocol/inspector",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["mcp", "protocol", "developer-tool"],
  ],
  [
    "mcp-rust-sdk-releases",
    "Model Context Protocol Rust SDK",
    "modelcontextprotocol/rust-sdk",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["mcp", "protocol", "sdk", "rust"],
  ],
  [
    "mcp-go-sdk-releases",
    "Model Context Protocol Go SDK",
    "modelcontextprotocol/go-sdk",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["mcp", "protocol", "sdk", "go"],
  ],

  // Evaluation, model engineering, data and infrastructure (25).
  [
    "guardrails-releases",
    "Guardrails AI",
    "guardrails-ai/guardrails",
    "GLOBAL",
    "research-eval",
    "primary",
    ["guardrails", "structured-output", "evaluation"],
  ],
  [
    "inspect-ai-releases",
    "Inspect AI",
    "UKGovernmentBEIS/inspect_ai",
    "UK",
    "research-eval",
    "policy",
    ["evaluation", "safety", "government"],
  ],
  [
    "deepeval-releases",
    "DeepEval",
    "confident-ai/deepeval",
    "GLOBAL",
    "research-eval",
    "primary",
    ["evaluation", "testing", "llmops"],
  ],
  [
    "ragas-releases",
    "Ragas",
    "explodinggradients/ragas",
    "GLOBAL",
    "research-eval",
    "primary",
    ["evaluation", "rag", "testing"],
  ],
  [
    "trulens-releases",
    "TruLens",
    "truera/trulens",
    "GLOBAL",
    "research-eval",
    "primary",
    ["evaluation", "observability", "rag"],
  ],
  [
    "braintrust-sdk-releases",
    "Braintrust SDK",
    "braintrustdata/braintrust-sdk",
    "GLOBAL",
    "research-eval",
    "primary",
    ["evaluation", "observability", "sdk"],
  ],
  [
    "mlflow-releases",
    "MLflow",
    "mlflow/mlflow",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["mlops", "observability", "model-lifecycle"],
  ],
  [
    "wandb-releases",
    "Weights & Biases",
    "wandb/wandb",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["mlops", "observability", "training"],
  ],
  [
    "bentoml-releases",
    "BentoML",
    "bentoml/BentoML",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["serving", "inference", "deployment"],
  ],
  [
    "kserve-releases",
    "KServe",
    "kserve/kserve",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["serving", "kubernetes", "inference"],
  ],
  [
    "kubeflow-pipelines-releases",
    "Kubeflow Pipelines",
    "kubeflow/pipelines",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["mlops", "workflow", "kubernetes"],
  ],
  [
    "skypilot-releases",
    "SkyPilot",
    "skypilot-org/skypilot",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["cloud", "orchestration", "gpu"],
  ],
  [
    "modal-client-releases",
    "Modal Client",
    "modal-labs/modal-client",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["cloud", "serverless", "inference"],
  ],
  [
    "pytorch-core-releases",
    "PyTorch Core",
    "pytorch/pytorch",
    "GLOBAL",
    "open-source",
    "primary",
    ["framework", "training", "inference"],
  ],
  [
    "tensorflow-core-releases",
    "TensorFlow Core",
    "tensorflow/tensorflow",
    "GLOBAL",
    "open-source",
    "primary",
    ["framework", "training", "inference"],
  ],
  [
    "keras-releases",
    "Keras",
    "keras-team/keras",
    "GLOBAL",
    "open-source",
    "primary",
    ["framework", "training", "developer"],
  ],
  [
    "accelerate-releases",
    "Hugging Face Accelerate",
    "huggingface/accelerate",
    "GLOBAL",
    "open-source",
    "primary",
    ["training", "distributed", "huggingface"],
  ],
  [
    "bitsandbytes-releases",
    "bitsandbytes",
    "bitsandbytes-foundation/bitsandbytes",
    "GLOBAL",
    "open-source",
    "primary",
    ["quantization", "training", "inference"],
  ],
  [
    "llama-cpp-python-releases",
    "llama-cpp-python",
    "abetlen/llama-cpp-python",
    "GLOBAL",
    "open-source",
    "primary",
    ["local-inference", "python", "llama.cpp"],
  ],
  [
    "lmcache-releases",
    "LMCache",
    "LMCache/LMCache",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["kv-cache", "inference", "serving"],
  ],
  [
    "ktransformers-releases",
    "KTransformers",
    "kvcache-ai/ktransformers",
    "CN",
    "open-source",
    "primary",
    ["local-inference", "optimization", "heterogeneous-compute"],
  ],
  [
    "executorch-releases",
    "ExecuTorch",
    "pytorch/executorch",
    "GLOBAL",
    "open-source",
    "primary",
    ["on-device", "inference", "edge"],
  ],
  [
    "openvino-releases",
    "OpenVINO",
    "openvinotoolkit/openvino",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["inference", "optimization", "edge"],
  ],
  [
    "docling-releases",
    "Docling",
    "docling-project/docling",
    "GLOBAL",
    "open-source",
    "primary",
    ["document-ai", "rag", "data-pipeline"],
  ],
  [
    "pgvector-releases",
    "pgvector",
    "pgvector/pgvector",
    "GLOBAL",
    "open-source",
    "primary",
    ["vector-database", "postgresql", "rag"],
  ],

  // China-first open-source products and engineering stacks (15).
  [
    "infinity-releases",
    "Infinity",
    "infiniflow/infinity",
    "CN",
    "china-lab",
    "primary",
    ["database", "rag", "search"],
  ],
  [
    "xinference-releases",
    "Xinference",
    "xorbitsai/inference",
    "CN",
    "china-lab",
    "primary",
    ["inference", "serving", "open-model"],
  ],
  [
    "qanything-releases",
    "QAnything",
    "netease-youdao/QAnything",
    "CN",
    "china-lab",
    "primary",
    ["rag", "enterprise", "knowledge-base"],
  ],
  [
    "chatbox-releases",
    "Chatbox",
    "chatboxai/chatbox",
    "CN",
    "china-lab",
    "primary",
    ["consumer", "desktop", "multi-model"],
  ],
  [
    "cherry-studio-releases",
    "Cherry Studio",
    "CherryHQ/cherry-studio",
    "CN",
    "china-lab",
    "primary",
    ["consumer", "desktop", "agent"],
  ],
  [
    "maxkb-releases",
    "MaxKB",
    "1Panel-dev/MaxKB",
    "CN",
    "china-lab",
    "primary",
    ["rag", "enterprise", "knowledge-base"],
  ],
  [
    "new-api-releases",
    "New API",
    "Calcium-Ion/new-api",
    "CN",
    "china-lab",
    "primary",
    ["model-gateway", "api", "cost"],
  ],
  [
    "bisheng-releases",
    "BISHENG",
    "dataelement/bisheng",
    "CN",
    "china-lab",
    "primary",
    ["agent", "enterprise", "workflow"],
  ],
  [
    "fastdeploy-releases",
    "Paddle FastDeploy",
    "PaddlePaddle/FastDeploy",
    "CN",
    "china-lab",
    "primary",
    ["inference", "deployment", "paddle"],
  ],
  [
    "paddlex-releases",
    "PaddleX",
    "PaddlePaddle/PaddleX",
    "CN",
    "china-lab",
    "primary",
    ["multimodal", "computer-vision", "paddle"],
  ],
  [
    "funasr-releases",
    "FunASR",
    "modelscope/FunASR",
    "CN",
    "china-lab",
    "research",
    ["speech", "audio", "modelscope"],
  ],
  [
    "sensevoice-releases",
    "SenseVoice",
    "FunAudioLLM/SenseVoice",
    "CN",
    "china-lab",
    "research",
    ["speech", "audio", "multilingual"],
  ],
  [
    "fish-speech-releases",
    "Fish Speech",
    "fishaudio/fish-speech",
    "CN",
    "china-lab",
    "research",
    ["speech", "audio", "generation"],
  ],
  [
    "minicpm-releases",
    "MiniCPM",
    "OpenBMB/MiniCPM",
    "CN",
    "china-lab",
    "research",
    ["small-model", "on-device", "multimodal"],
  ],
  [
    "metagpt-releases",
    "MetaGPT",
    "FoundationAgents/MetaGPT",
    "CN",
    "china-lab",
    "research",
    ["multi-agent", "software-engineering", "agent"],
  ],

  // Robotics, embodied intelligence and vision (10).
  [
    "lerobot-releases",
    "LeRobot",
    "huggingface/lerobot",
    "GLOBAL",
    "robotics",
    "research",
    ["robotics", "embodied-ai", "open-source"],
  ],
  [
    "isaaclab-releases",
    "NVIDIA Isaac Lab",
    "isaac-sim/IsaacLab",
    "GLOBAL",
    "robotics",
    "primary",
    ["robotics", "simulation", "training"],
  ],
  [
    "mujoco-releases",
    "MuJoCo",
    "google-deepmind/mujoco",
    "GLOBAL",
    "robotics",
    "research",
    ["robotics", "simulation", "physics"],
  ],
  [
    "genesis-releases",
    "Genesis",
    "Genesis-Embodied-AI/Genesis",
    "GLOBAL",
    "robotics",
    "research",
    ["robotics", "simulation", "world-model"],
  ],
  [
    "sapien-releases",
    "SAPIEN",
    "haosulab/SAPIEN",
    "GLOBAL",
    "robotics",
    "research",
    ["robotics", "simulation", "embodied-ai"],
  ],
  [
    "maniskill-releases",
    "ManiSkill",
    "haosulab/ManiSkill",
    "GLOBAL",
    "robotics",
    "research",
    ["robotics", "benchmark", "manipulation"],
  ],
  [
    "moveit2-releases",
    "MoveIt 2",
    "moveit/moveit2",
    "GLOBAL",
    "robotics",
    "primary",
    ["robotics", "motion-planning", "ros"],
  ],
  [
    "ros2-releases",
    "ROS 2",
    "ros2/ros2",
    "GLOBAL",
    "robotics",
    "primary",
    ["robotics", "middleware", "ros"],
  ],
  [
    "navigation2-releases",
    "Navigation2",
    "ros-navigation/navigation2",
    "GLOBAL",
    "robotics",
    "primary",
    ["robotics", "navigation", "ros"],
  ],
  [
    "ultralytics-releases",
    "Ultralytics",
    "ultralytics/ultralytics",
    "GLOBAL",
    "robotics",
    "primary",
    ["computer-vision", "edge", "perception"],
  ],
];

const feedSeeds: FeedSeed[] = [
  [
    "meta-engineering-ai-feed",
    "Meta Engineering AI Research",
    "https://engineering.fb.com/category/ai-research/",
    "https://engineering.fb.com/category/ai-research/feed/",
    "GLOBAL",
    "frontier-lab",
    "research",
    ["research", "systems", "open-model"],
  ],
  [
    "cisa-news-feed",
    "Cybersecurity and Infrastructure Security Agency News",
    "https://www.cisa.gov/news-events/news",
    "https://www.cisa.gov/news.xml",
    "US",
    "policy",
    "policy",
    ["ai-security", "critical-infrastructure", "cybersecurity"],
  ],
  [
    "redhat-ai-feed",
    "Red Hat AI",
    "https://www.redhat.com/en/blog/channel/artificial-intelligence",
    "https://www.redhat.com/en/rss/blog/channel/artificial-intelligence",
    "US",
    "infra-chip-cloud",
    "primary",
    ["enterprise", "open-source", "platform"],
  ],
  [
    "github-ai-ml-feed",
    "GitHub AI & ML",
    "https://github.blog/ai-and-ml/",
    "https://github.blog/ai-and-ml/feed/",
    "GLOBAL",
    "agent-devtool",
    "primary",
    ["developer", "ai-coding", "platform"],
  ],
  [
    "weaviate-blog-feed",
    "Weaviate Blog",
    "https://weaviate.io/blog",
    "https://weaviate.io/blog/rss.xml",
    "EU",
    "open-source",
    "primary",
    ["vector-database", "rag", "enterprise"],
  ],
  [
    "qdrant-blog-feed",
    "Qdrant Blog",
    "https://qdrant.tech/blog/",
    "https://qdrant.tech/blog/index.xml",
    "EU",
    "open-source",
    "primary",
    ["vector-database", "rag", "inference"],
  ],
  [
    "arize-blog-feed",
    "Arize AI Blog",
    "https://arize.com/blog/",
    "https://arize.com/blog/feed/",
    "US",
    "research-eval",
    "primary",
    ["evaluation", "observability", "llmops"],
  ],
  [
    "mlflow-blog-feed",
    "MLflow Blog",
    "https://mlflow.org/blog/",
    "https://mlflow.org/blog/rss.xml",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["mlops", "observability", "model-lifecycle"],
  ],
  [
    "mozilla-ai-feed",
    "Mozilla AI Blog",
    "https://blog.mozilla.ai/",
    "https://blog.mozilla.ai/rss/",
    "GLOBAL",
    "frontier-lab",
    "research",
    ["open-source", "trustworthy-ai", "consumer"],
  ],
  [
    "cncf-blog-feed",
    "Cloud Native Computing Foundation Blog",
    "https://www.cncf.io/blog/",
    "https://www.cncf.io/blog/feed/",
    "GLOBAL",
    "infra-chip-cloud",
    "primary",
    ["cloud-native", "infrastructure", "ai-platform"],
  ],
  [
    "mit-csail-feed",
    "MIT CSAIL News",
    "https://www.csail.mit.edu/news",
    "https://www.csail.mit.edu/rss.xml",
    "US",
    "research-eval",
    "research",
    ["research", "robotics", "systems"],
  ],
  [
    "cmu-ml-feed",
    "Carnegie Mellon ML Blog",
    "https://blog.ml.cmu.edu/",
    "https://blog.ml.cmu.edu/feed/",
    "US",
    "research-eval",
    "research",
    ["research", "machine-learning", "education"],
  ],
  [
    "princeton-nlp-feed",
    "Princeton NLP",
    "https://princeton-nlp.github.io/",
    "https://princeton-nlp.github.io/feed.xml",
    "US",
    "research-eval",
    "research",
    ["research", "nlp", "evaluation"],
  ],
  [
    "gradient-feed",
    "The Gradient",
    "https://thegradient.pub/",
    "https://thegradient.pub/rss/",
    "GLOBAL",
    "media",
    "media",
    ["research", "analysis", "community"],
    2,
  ],
  [
    "sec-press-releases-feed",
    "SEC Press Releases",
    "https://www.sec.gov/newsroom/press-releases",
    "https://www.sec.gov/news/pressreleases.rss",
    "US",
    "capital-business",
    "policy",
    ["filing", "enforcement", "market-structure"],
  ],
  [
    "federal-reserve-press-feed",
    "Federal Reserve Press Releases",
    "https://www.federalreserve.gov/newsevents/pressreleases.htm",
    "https://www.federalreserve.gov/feeds/press_all.xml",
    "US",
    "policy",
    "policy",
    ["macro", "rates", "liquidity"],
  ],
  [
    "uk-dsit-feed",
    "UK Department for Science, Innovation and Technology",
    "https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology",
    "https://www.gov.uk/government/organisations/department-for-science-innovation-and-technology.atom",
    "UK",
    "policy",
    "policy",
    ["policy", "ai-safety", "innovation"],
  ],
  [
    "radical-ventures-feed",
    "Radical Ventures",
    "https://radical.vc/",
    "https://radical.vc/feed/",
    "GLOBAL",
    "capital-business",
    "expert",
    ["venture-capital", "ai-company", "market"],
    2,
  ],
  [
    "air-street-press-feed",
    "Air Street Press",
    "https://press.airstreet.com/",
    "https://press.airstreet.com/feed",
    "UK",
    "capital-business",
    "expert",
    ["venture-capital", "research", "market"],
    2,
  ],
  [
    "ycombinator-blog-feed",
    "Y Combinator Blog",
    "https://www.ycombinator.com/blog",
    "https://www.ycombinator.com/blog/rss",
    "US",
    "capital-business",
    "primary",
    ["startup", "product", "venture-capital"],
    2,
  ],
];

function releaseSource(seed: ReleaseSeed): CatalogSource {
  const [slug, name, repository, region, category, role, topics, tier = 1] = seed;
  const homepageUrl = `https://github.com/${repository}`;
  return {
    slug,
    name,
    homepageUrl,
    endpoint: `${homepageUrl}/releases.atom`,
    adapter: "github-releases",
    tier,
    role,
    region,
    language: region === "CN" ? "zh-CN" : "en",
    authorityScore: tier === 1 ? 92 : 78,
    qualityScore: tier === 1 ? 84 : 74,
    enabled: false,
    lifecycleStatus: "shadow",
    category,
    acquisition: "github",
    topics: [...topics],
    maintenanceStatus: "candidate",
    cadence: tier === 1 ? "6h" : "12h",
    licenseNote:
      "Official project release metadata and provenance only; retain links and do not republish full release bodies.",
  };
}

function feedSource(seed: FeedSeed): CatalogSource {
  const [slug, name, homepageUrl, endpoint, region, category, role, topics, tier = 1] = seed;
  return {
    slug,
    name,
    homepageUrl,
    endpoint,
    adapter: "rss",
    tier,
    role,
    region,
    language: "en",
    authorityScore: tier === 1 ? 92 : 78,
    qualityScore: tier === 1 ? 84 : 74,
    enabled: false,
    lifecycleStatus: "shadow",
    category,
    acquisition: "rss",
    topics: [...topics],
    maintenanceStatus: "candidate",
    cadence: role === "policy" ? "12h" : "6h",
    licenseNote:
      "Public feed metadata, short excerpts and provenance only; link to the original and do not republish full articles.",
    identityHosts: [new URL(homepageUrl).hostname],
  };
}

export const sourceExpansionWave20260713: CatalogSource[] = [
  ...releaseSeeds.map(releaseSource),
  ...feedSeeds.map(feedSource),
];
